debug: false
server:
  port: 0
  tomcat:
    max-threads: 1000
    uri-encoding: UTF-8
management:
  endpoints:
    web:
      exposure:
        include: health,info,hystrix.stream
# ===============================
# = Spring Config
# ===============================
spring:
  thymeleaf:
    cache: false
# ===============================
# = Eureka Config
# ===============================
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
# ===============================
# = Security Config
# ===============================
security:
  oauth2:
    client:
      client-id: client
      client-secret: client
    resource:
      token-info-uri: http://127.0.0.1:8770/oauth/2.0/oauth/check_token
      user-info-uri:  http://127.0.0.1:8770/oauth/2.0/user
      prefer-token-info: false
# ===============================
# = Ribbon Config
# ===============================
feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000
        loggerLevel: full
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 11000